version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: muzayede_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: muzayede_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/data/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./backend/data/20251812_2330.sql:/docker-entrypoint-initdb.d/03_20251812_2330.sql
      - ./backend/data/migration.sql:/docker-entrypoint-initdb.d/02_migration.sql
      - ./backend/data/migration_images_db.sql:/docker-entrypoint-initdb.d/04_migration_images_db.sql
      - ./backend/data/migration_increase_decimal_20.sql:/docker-entrypoint-initdb.d/06_migration_increase_decimal_20.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: muzayede_backend
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: muzayede_db
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: muzayede_frontend
    environment:
      API_BASE_URL: http://backend:3000/api
      PUBLIC_API_URL: http://145.223.100.162:3000
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
